[wip] Feature/ux impovements
dialectlabs/react pull request #119
Opened 2022-05-31 17:20 UTC by Kiryous

2022-06-01 11:08 UTC, fsher requested changes
Well done, sir! This was quite a read. Haven't considered using react-transition-group before, but totally makes sense. I think at some point we need to either remove `@headlessui/react` package and convert our transitions to `react-transition-group`, since it's more flexible, but definitely, need to think this through.

Either way, left some comments, please take a look when you have time!

2022-06-01 11:08 UTC, fsher commented on packages/dialect-react-ui/components/Chat/screens/Main/pages/ThreadPage/MessageInput.tsx
> +              {/* <icons.arrownarrowright className="dt-h-4 dt-w-4" /> */}
Please remove the commented out parts, since I see that we use a unicode error now. Unless there is a reason to keep this?

2022-06-01 11:08 UTC, fsher commented on packages/dialect-react-ui/components/Chat/screens/Main/pages/ThreadPage/Thread.tsx
> +    sendMessage(messageText, dialect?.dialect.encrypted, id).catch((err) =>
`.catch(handleError)`

2022-06-01 11:08 UTC, fsher commented on packages/dialect-react-ui/components/Chat/screens/Main/pages/ThreadPage/Thread.tsx
> +                  <CSSTransition
Nicely done! 💅

2022-06-01 11:08 UTC, fsher commented on packages/dialect-react-ui/components/Icon/ArrowClockwise.tsx
> +    fill="none"
Please add `viewBox` and `preserveAspectRatio="xMidYMid meet"` props to our SVGs in case we need to scale them.

2022-06-08 17:10 UTC, Kiryous commented on packages/dialect-react/components/DialectContext/index.tsx
> +        if (thread?.length) {
Thanks for detailed suggestion, cleaned this up!

2022-06-08 18:30 UTC, Kiryous commented on packages/dialect-react-ui/components/Chat/screens/Main/ThreadsList/MessagePreview.tsx
> +}: {
because sending messsages are appened to the ones in dialect, it's good to refactor, but I'll leave it for subsequent PR

2022-06-08 18:41 UTC, merged