Fix typing long msg without space will expand whole chat
dialectlabs/react pull request #53
Opened 2022-04-06 14:24 UTC by 0xkokoro

When you type a long msg without space for instance when you type a long URL or an address, the msg will expand the whole chat unexpectedly. Use won't be able to see the send button or other msgs.

**Before:**
https://user-images.githubusercontent.com/93460079/161997413-5ee5658e-c68a-4b55-a2ec-b777b1bf64cc.mov

**After:**
https://user-images.githubusercontent.com/93460079/161997539-fcb1fc25-d323-467f-aa14-b5fc66f25f66.mov

2022-04-06 14:30 UTC, 0xkokoro commented on packages/dialect-react-ui/components/Chat/screens/Main/pages/ThreadPage/MessageInput.tsx
> +                style={{ width: '29rem'}}
This is the default chat width of the parent container but for some reason it got overwritten here.

2022-04-06 14:56 UTC, zhelezkov requested changes
fixed width doesn't seems as a good fix, since it prevents text area resizing in inbox mode
Please see attached screenshot 
<img width="1359" alt="Screenshot 2022-04-06 at 18 56 01" src="https://user-images.githubusercontent.com/5163918/162004258-111ec14b-1bc2-4137-986b-1b1c34c3216a.png">

2022-04-14 10:13 UTC, Kiryous requested changes
Please find a solution without fixed width; It seems there is a need to do some magic with flex-grow of messaging column

2022-04-20 20:35 UTC, cbosborn commented
@0xkokoro thanks for working on this. do we want to close this PR or find a solution for it?

2022-04-21 16:55 UTC, Kiryous commented
btw, guys! I gonna pick up this one, found a simple solution

2022-04-21 17:09 UTC, Kiryous commented
Fixed in https://github.com/dialectlabs/react/pull/84

2022-04-21 17:29 UTC, closed without merging